In [3]:
import numpy as np

def parse_sign_matrix(text):
    """conver + to +1, - to -1"""
    lines = [line.strip() for line in text.strip().splitlines() if line.strip()]
    return np.array([[1 if c == '+' else -1 for c in line] for line in lines], dtype=int)

def normalize_pm_matrix(H):
    """normalize ±1 matrix s.t. first row and first column are all +1"""
    H = H.copy()
    n = len(H)
    for j in range(n):
        if H[0, j] == -1: H[:, j] *= -1
    for i in range(n):
        if H[i, 0] == -1: H[i, :] *= -1
    return H

def reduce_to_01_matrix(text):
    """conver NxN ±1 matrix to (N-1)x(N-1) 0/1 matrix"""
    H = normalize_pm_matrix(parse_sign_matrix(text))
    B = H[1:, 1:]
    A = (1 - B) // 2   # +1→0, -1→1
    return A


text = """
+++++-+++--+-
-+++++-+++--+
+-+++++-+++--
-+-+++++-+++-
--+-+++++-+++
+--+-+++++-++
++--+-+++++-+
+++--+-+++++-
-+++--+-+++++
+-+++--+-++++
++-+++--+-+++
+++-+++--+-++
++++-+++--+-+
"""
A = reduce_to_01_matrix(text)
print("0/1 matrix:\n", A)
# det of A
print(abs(np.linalg.det(A)))


0/1 matrix:
 [[1 1 1 1 0 0 1 1 0 1 0 0]
 [1 0 0 0 1 0 1 0 1 1 1 0]
 [1 0 1 1 0 1 1 0 0 0 1 1]
 [0 1 0 1 0 1 1 1 1 0 1 0]
 [1 1 0 1 1 0 0 0 1 0 0 1]
 [0 1 1 0 0 0 0 0 1 1 1 1]
 [0 0 1 1 1 1 0 0 1 1 0 0]
 [1 1 1 0 1 1 0 1 0 0 1 0]
 [1 0 0 0 0 1 0 1 1 1 0 1]
 [0 1 0 0 1 1 1 0 0 1 0 1]
 [0 0 1 0 1 0 1 1 1 0 0 1]
 [0 0 0 1 1 0 0 1 0 1 1 1]]
3645.000000000004


In [11]:
# each row is a matrix, reshape it to 11 x 11 matrix
A = "01111011100,11011000111,00001111101,00111110110,11011110000,01101100001,10110101101,11001101110,10101011011,11100010101,01010111011"
A = np.array([[int(c) for c in row] for row in A.split(",")], dtype=int)
print("0/1 matrix:\n", A)

# calculate det
print(abs(np.linalg.det(A)))

0/1 matrix:
 [[0 1 1 1 1 0 1 1 1 0 0]
 [1 1 0 1 1 0 0 0 1 1 1]
 [0 0 0 0 1 1 1 1 1 0 1]
 [0 0 1 1 1 1 1 0 1 1 0]
 [1 1 0 1 1 1 1 0 0 0 0]
 [0 1 1 0 1 1 0 0 0 0 1]
 [1 0 1 1 0 1 0 1 1 0 1]
 [1 1 0 0 1 1 0 1 1 1 0]
 [1 0 1 0 1 0 1 1 0 1 1]
 [1 1 1 0 0 0 1 0 1 0 1]
 [0 1 0 1 0 1 1 1 0 1 1]]
765.0000000000007


In [14]:
# 读入数据
data = """00110110110,00101101101,11000111100,10001110011,01010101011,11111100000,10110011001,01101011010,11100000111,10011001110,01011010101
00001101011,10111011001,11110101010,01011110000,10101110110,00110110101,01100010011,01101001100,11101100001,11000111101,11011000111
00110111101,10000101111,11001110100,10011011010,11100010011,01110100010,11010001100,10111000001,01101001110,01011010111,01001101001
00101011100,10010110110,11011001010,10111100000,11110000101,10100011011,01100100110,01111010011,01010111001,00011101111,11001110101
00011100101,10110110100,01000111101,10011011110,11010010011,00110001111,11000100110,01111010110,00101110011,11111101000,11101000101
01100111011,01011000111,11001110000,10111100001,01110010100,10101010111,11100100110,11111001010,10010111111,00101101100,11000001101
11001100110,11111101001,11000010101,01101011010,10100110011,00111110100,10110001110,00101000111,10011010011,01010111111,10001111101
00011001011,01110001101,10111010000,11010001110,11001111001,11101100011,10010110111,00101101100,10100011111,01110111010,01001010110
11110001010,10010110110,11101111000,10110100001,00110011101,10101010111,01100100111,01011010011,10000111011,00111101010,11011001101
00111110011,11110011001,10110101010,11000111011,11011100001,10100110100,10011011110,01110000110,10101001111,01101111000,00010101101
00011001111,10101011101,11001111010,11111000001,10110001010,10101100110,10010101101,01100101011,00111110011,11000010111,01110111100
10001011001,11011100010,01011111100,10000110110,11110010000,00110101010,11000101101,00111100101,11101001110,01010010111,01101110011
01111010100,01111100011,01000110111,10011110110,10100010011,00110111010,11010001110,10110100101,11101101100,00001001111,11011111001
00001110101,10010111110,00011000110,10110100101,11011010000,01110110010,01010101011,11101101100,10101011011,11000000111,01110011101
11000011101,11000100110,00010111100,10101010110,01110010011,11111111000,10100101011,10110000101,01011001110,10011110011,01101100101
11001011000,11100101100,10010110101,10111000111,01100010101,10100111011,00111101001,00010011110,01110110010,01001100111,00101110100
11101100010,10110110111,01110111000,00111100001,01101010100,10101011001,01100001111,01011010011,00001111111,10111001110,11011101101
01101101011,01000110110,00111110100,10100100111,01100011101,10101011010,11110101000,01110010011,00010111011,00110001110,11011000101
10110101011,01111100110,11001001101,00101011011,11100110001,10110010101,10111111000,11011010011,11100011110,10001110111,01010111101
01111011100,11011000111,00001111101,00111110110,11011110000,01101100001,10110101101,11001101110,10101011011,11100010101,01010111011
"""  

# 按行分割
lines = [line.strip() for line in data.strip().split("\n") if line.strip()]

# 用集合去重（防止相同矩阵重复计算）
unique_lines = list(set(lines))

det_counts = {}

for line in unique_lines:
    # 把一行的逗号分隔部分转成二维矩阵
    rows = line.split(',')
    matrix = np.array([[int(c) for c in row] for row in rows])

    # 计算行列式
    det = round(np.linalg.det(matrix))  # 可四舍五入成整数
    det_counts[det] = det_counts.get(det, 0) + 1

# 打印结果
for det_val, count in sorted(det_counts.items()):
    print(f"det = {det_val}, count = {count}")
    
print(" number of different det:")
print(len(det_counts))


det = -1458, count = 1
det = -945, count = 1
det = -801, count = 1
det = -798, count = 1
det = -786, count = 1
det = -784, count = 1
det = -777, count = 1
det = -776, count = 1
det = -774, count = 1
det = -773, count = 1
det = -768, count = 2
det = 765, count = 1
det = 768, count = 1
det = 772, count = 1
det = 777, count = 1
det = 785, count = 1
det = 786, count = 1
det = 798, count = 1
det = 807, count = 1
 number of different det:
19
