In [20]:
import numpy as np

def parse_sign_matrix(text):
    """conver + to +1, - to -1"""
    lines = [line.strip() for line in text.strip().splitlines() if line.strip()]
    return np.array([[1 if c == '+' else -1 for c in line] for line in lines], dtype=int)

def normalize_pm_matrix(H):
    """normalize ±1 matrix s.t. first row and first column are all +1"""
    H = H.copy()
    n = len(H)
    for j in range(n):
        if H[0, j] == -1: H[:, j] *= -1
    for i in range(n):
        if H[i, 0] == -1: H[i, :] *= -1
    return H

def reduce_to_01_matrix(text):
    """conver NxN ±1 matrix to (N-1)x(N-1) 0/1 matrix"""
    H = normalize_pm_matrix(parse_sign_matrix(text))
    B = H[1:, 1:]
    A = (1 - B) // 2   # +1→0, -1→1
    return A


text = """
+++++-+++--+-
-+++++-+++--+
+-+++++-+++--
-+-+++++-+++-
--+-+++++-+++
+--+-+++++-++
++--+-+++++-+
+++--+-+++++-
-+++--+-+++++
+-+++--+-++++
++-+++--+-+++
+++-+++--+-++
++++-+++--+-+
"""
A = reduce_to_01_matrix(text)
print("0/1 matrix:\n", A)
# det of A
print(abs(np.linalg.det(A)))


0/1 matrix:
 [[1 1 1 1 0 0 1 1 0 1 0 0]
 [1 0 0 0 1 0 1 0 1 1 1 0]
 [1 0 1 1 0 1 1 0 0 0 1 1]
 [0 1 0 1 0 1 1 1 1 0 1 0]
 [1 1 0 1 1 0 0 0 1 0 0 1]
 [0 1 1 0 0 0 0 0 1 1 1 1]
 [0 0 1 1 1 1 0 0 1 1 0 0]
 [1 1 1 0 1 1 0 1 0 0 1 0]
 [1 0 0 0 0 1 0 1 1 1 0 1]
 [0 1 0 0 1 1 1 0 0 1 0 1]
 [0 0 1 0 1 0 1 1 1 0 0 1]
 [0 0 0 1 1 0 0 1 0 1 1 1]]
3645.000000000004
