In [1]:
import numpy as np

def parse_sign_matrix(text):
    """conver + to +1, - to -1"""
    lines = [line.strip() for line in text.strip().splitlines() if line.strip()]
    return np.array([[1 if c == '+' else -1 for c in line] for line in lines], dtype=int)

def normalize_pm_matrix(H):
    """normalize ±1 matrix s.t. first row and first column are all +1"""
    H = H.copy()
    n = len(H)
    for j in range(n):
        if H[0, j] == -1: H[:, j] *= -1
    for i in range(n):
        if H[i, 0] == -1: H[i, :] *= -1
    return H

def reduce_to_01_matrix(text):
    """conver NxN ±1 matrix to (N-1)x(N-1) 0/1 matrix"""
    H = normalize_pm_matrix(parse_sign_matrix(text))
    B = H[1:, 1:]
    A = (1 - B) // 2   # +1→0, -1→1
    return A


text = """
+++++++++++++++++
+----------++++++
+------++++----++
+++----+--++--+--
++--+---+-+-++---
+--+-+---++++----
+-+---+-++--+-+--
+---+-++-+-+-+---
+--+-+-++----++--
+---+++---+---+-+
+-++--+---+--+-+-
+++--+---+---+--+
++---+++----+--+-
++-+--+-+--+----+
++-++----+----++-
+-+++--+----+---+
+-+-++--+--+---+-
"""
A = reduce_to_01_matrix(text)
print("0/1 matrix:\n", A)
# det of A
print(abs(np.linalg.det(A)))

formatted = "upper_bound_matrix = [\n    " + ";\n    ".join(
    [" ".join(map(str, row)) for row in A]
) + "\n];"

print(formatted)

0/1 matrix:
 [[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 0 0 0 0 1 1 1 1 0 0]
 [0 0 1 1 1 1 0 1 1 0 0 1 1 0 1 1]
 [0 1 1 0 1 1 1 0 1 0 1 0 0 1 1 1]
 [1 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1]
 [1 0 1 1 1 0 1 0 0 1 1 0 1 0 1 1]
 [1 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1]
 [1 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1]
 [1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0]
 [1 0 0 1 1 0 1 1 1 0 1 1 0 1 0 1]
 [0 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0]
 [0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1]
 [0 1 0 1 1 0 1 0 1 1 0 1 1 1 1 0]
 [0 1 0 0 1 1 1 1 0 1 1 1 1 0 0 1]
 [1 0 0 0 1 1 0 1 1 1 1 0 1 1 1 0]
 [1 0 1 0 0 1 1 0 1 1 0 1 1 1 0 1]]
327680.00000000023
upper_bound_matrix = [
    1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0;
    1 1 1 1 1 1 0 0 0 0 1 1 1 1 0 0;
    0 0 1 1 1 1 0 1 1 0 0 1 1 0 1 1;
    0 1 1 0 1 1 1 0 1 0 1 0 0 1 1 1;
    1 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1;
    1 0 1 1 1 0 1 0 0 1 1 0 1 0 1 1;
    1 1 1 0 1 0 0 1 0 1 0 1 0 1 1 1;
    1 1 0 1 0 1 0 0 1 1 1 1 0 0 1 1;
    1 1 1 0 0 0 1 1 1 0 1 1 1 0 1 0;
    1 0 0 1 1 0 1 1 1 0 1 1 0 1 0 1;
    0 0 1 1 0 

In [11]:
# each row is a matrix, reshape it to 11 x 11 matrix
A = "01111011100,11011000111,00001111101,00111110110,11011110000,01101100001,10110101101,11001101110,10101011011,11100010101,01010111011"
A = np.array([[int(c) for c in row] for row in A.split(",")], dtype=int)
print("0/1 matrix:\n", A)

# calculate det
print(abs(np.linalg.det(A)))

0/1 matrix:
 [[0 1 1 1 1 0 1 1 1 0 0]
 [1 1 0 1 1 0 0 0 1 1 1]
 [0 0 0 0 1 1 1 1 1 0 1]
 [0 0 1 1 1 1 1 0 1 1 0]
 [1 1 0 1 1 1 1 0 0 0 0]
 [0 1 1 0 1 1 0 0 0 0 1]
 [1 0 1 1 0 1 0 1 1 0 1]
 [1 1 0 0 1 1 0 1 1 1 0]
 [1 0 1 0 1 0 1 1 0 1 1]
 [1 1 1 0 0 0 1 0 1 0 1]
 [0 1 0 1 0 1 1 1 0 1 1]]
765.0000000000007


In [ ]:
# 读入数据
data = """00110110110,00101101101,11000111100,10001110011,01010101011,11111100000,10110011001,01101011010,11100000111,10011001110,01011010101
00110101011,01000011111,00111010001,00001110111,11001101001,11100110010,11010000111,10010111100,01011011010,10101001110,01111100100
01010110011,00111000111,11000100101,01111010100,11001011011,11110001010,10011101001,10010011110,00100111101,01001101110,10101110010
11011110000,00110110101,10111011100,11010000101,11000111110,01001011011,11100101001,11110010010,10010101011,10101100111,01111101110
10000101101,10101100110,10011011110,11011010101,10110110011,11100001011,01000110111,01011101011,11001111000,01110101100,00101011101
01011111001,10001111010,10010011101,00101110101,00011100111,10110110010,11001010011,11100101111,11011100100,10111001001,01111011110
11110011000,10111100010,00010111101,10001011100,11000110011,00101011011,10100010111,11011001111,01011010110,01100101110,01101100101
00110100101,10111000110,00101101011,01011110011,10111011000,11110101010,11100010011,11001001101,01101110100,10000111110,01110011110
10101001101,01001010001,11000001110,01110001011,10011011010,00010111101,11111100100,11100111000,10100010111,00101111110,10001100011
01110100100,11000101110,11111101000,10110100011,01011110010,00001101101,10101010110,11100110001,11011000101,01110011011,10010111100
01011011011,11010110001,01100011101,00111111000,11101110010,10010011110,01110100110,10110001011,11111000100,00111010111,10001101101
01000011011,10000110110,01011110101,01101010100,01101100010,11011001110,00110101110,10111010011,11110000111,11110111000,10101101101
10110000111,01011001011,00001110111,11011100100,01100010101,00011011100,10101101101,01110101110,11101011010,00111110001,11010111001
00010101001,01111100100,01100011110,10001101110,11010110000,11101001001,11010000111,00111110011,10111011100,10100110101,01001010101
10011011010,00011100111,01110011110,10110110001,10100101110,10010001101,01011101000,00000111011,11001110101,00101011101,11101000011
10011000011,11011011001,00110110101,00011011110,11010101110,01001110111,10000111011,10101101100,01100001011,11100010110,01111110010
10101101001,10110100101,10110001010,00000101111,01111100011,10011010111,11011001100,01100011101,11010111001,11101110110,00111111100
01011010110,11011001011,10111100100,00011111001,00101001111,01110101010,10110011010,10010101111,11100110011,11001111100,01110011101
01101110011,10101101010,01100101101,01110011110,10111011001,11110100011,00111100111,11001001111,11011110100,00010111011,10100010111
01001001110,10100010111,11011100100,00111001101,01011010101,01101100011,01100111100,00111110010,10001111001,00010101111,11110011011
11000011100,11011100101,01100110011,10101010101,10110011001,11011010010,10010110110,11110000110,00011001111,01111111100,10101101010
00110010111,10101111110,01100110011,01101100101,01101001011,11111010000,00110111001,11110101110,11000011101,01011111110,10011100011
10101111100,11001100111,11100010101,00111000111,01101011011,11111001001,00010111001,01110101110,10010011110,01011010100,11111110010
00111111011,10001101111,10110010111,11100101010,11011010010,11101011001,11111100001,01010111101,01101110110,10111111100,01111001110
01011100011,10101110001,11010100101,00100110111,01101101100,11111010110,00011011101,11001011111,01110011001,10110001011,10010111010
11100001111,10111100110,01110010100,10110011001,11101111000,00101010011,10001110101,00000111110,01011101001,11011011010,11010110011
01001101011,10010111110,11000010111,01110110100,00111000111,11011001100,11110001011,10100111101,10011110001,00101011010,11101100010
10000111101,00011111100,10011001111,01100101110,11010110010,01010011001,00110010110,00111100011,01001010111,11111000100,10101011010
01100011011,10110011101,11111101000,00010110011,00101111110,10000101111,10101000011,11001110001,01100100101,11110010110,01011001111
01101101001,00000110101,01010100110,10010101011,11110011100,10101000111,11011110001,00011001101,01000011011,00111110010,10001111110
11000011111,01101000011,11011100100,00110001110,11110101001,00011111011,10100100111,01110110010,01101111101,10111010001,10101111010
10111100100,10010011100,10101010101,11000100110,11110010001,11001101001,10100101011,00011110011,01111001111,01100111100,11101011010
11001101001,00100100111,00110111101,11010110011,00101111010,10001110100,11100011100,10111000001,01011011111,10010101110,01111100100
01000001101,10010110101,11111011000,11001000011,01100110011,10001111110,11010101010,01011000110,00011101001,10110001111,11101100100
01110001101,11000100111,01010111010,00100110011,01101101110,11111010010,11001111001,10110111100,00001011111,00011110101,10011101011
10111011100,11001010011,01101001001,10100101011,11010011001,00110010111,11110000010,01000001110,11011100101,11100110100,01011111010
11100010110,01100110101,00010111111,10100111000,01011110010,11001011001,11010101100,10001100111,11110000011,00111010100,01101001110
01101001111,01111110000,01010111011,10011101010,11001010010,10101111001,10110010111,11110001000,11100100011,11000111100,11011000101
10010111011,00111001011,01110111101,10111110000,11001011001,11110001110,11100100011,10011100101,01011010110,00101111110,10100010111
11110001100,10011001010,11010110010,10100010111,01100101011,10111110001,11000011001,00010111101,01111010111,11001100101,00101111100
11011100011,11011001100,10000110101,10110101110,01001111010,11100101001,00111011001,01111100100,01000001111,11110010010,10101000110
00110101101,01011100011,10000111001,01110010011,01101111000,11011011100,11101001001,00001011111,11100100110,10111110101,10111001010
01100110011,10010110101,10110001011,10111110000,01011011001,01010101010,11001100011,01101101101,11110000100,10001011110,00111000111
11100111010,10001101011,11010000110,01011110000,00010111101,10110100001,00101110111,11001010101,01111011011,10111011100,01101101100
11101000011,10011010111,10110100010,10001101100,01010001111,11111011000,00110100101,10100011111,11000110001,01101110110,00001111011
01100101100,00111110001,11111000100,10001011101,01110011011,10100010110,11001110000,00011111110,10101101010,10010100111,01001000111
10010011111,01010101110,01111010110,01001110101,01111001001,11001011010,10011100100,00100111100,11110110000,11100100111,00111110011
01000110011,10100111111,11010100110,11001001011,00111111010,01101101100,00011011101,10111100001,01110000111,11101010100,11110011000
11101010101,11100110110,00111100101,00010010111,00101111011,01111010010,11011100011,11110011001,01100001111,10111001110,01011111100
10101001101,00110010101,10011100010,00001111111,01010001110,11101010011,11001010100,10100111110,11010111001,01100100101,01111111000
11011001101,10010010111,01101110101,01010111110,11110100011,01110011011,00011101011,10100101111,00111000110,10110111000,11001011010
00001111010,10101100110,00111101001,10011011100,10010110111,11100111101,00100011111,11101010011,01001001111,11110001010,01111110100
11010110100,10100011101,00111110010,01001111001,01010011011,01110100111,11100101010,10011101111,01101001110,11111001001,11001010011
10101001110,10010011011,01100101111,00111111000,01011000110,11001110100,10111100101,11001001001,11110011100,01101010011,11110100010
00101101010,00011101001,01010111010,11100111001,10110100111,10111011100,11001100100,10001010011,11111000010,01111110101,01000001111
11111011100,01011101001,10110100001,10010001111,10011110010,10101101100,00110111110,00101011011,01111000111,11100001010,11000110101
11001010101,00111110100,11000111000,01011010010,10101011011,11110100011,01101101110,10011001100,01011101001,00000110111,01110011101
11001010111,10011100110,11100101010,11011011100,01101110100,11110000101,10101111001,01111001011,10110010010,11010110001,00010111111
11101000101,11001011000,00111010011,00111001110,10011100011,01001110110,11110110000,11010011111,01100101011,00011111101,10100111110
10010101110,01011100110,00111001011,00110010110,10001011111,10101110000,11111001100,11100100111,01100111010,11010010011,00010111101
11111100100,00100110111,10101011101,11000111110,01101101010,10001110011,00011011110,11110010011,10010101111,10110111000,01011111001
00001111011,10101100101,10100110110,00111011100,01101001110,11110001011,01111100010,10010101110,11001111000,11011010111,01010111101
11011100001,10000110111,00110011001,11010011100,00011111010,10101101100,01101011011,10111000110,01010101111,11110100010,01111110100
01010011111,11011011100,10001110111,11100001110,01110110100,10110111001,01001111010,00011101110,00101011101,01111000011,01001101101
00011101011,11110110010,00110111100,10100011011,01111011001,10011010100,01101011110,11010001110,00110000111,11101100101,01000110111
00111110011,10010110110,00110000111,11110011010,11011010101,00001011111,11000100011,01100111101,11101000110,10111101001,01011101110
11010100110,01011101001,00011110111,01000011101,11001010011,10000101011,01110011010,10110000101,01101100111,10101111100,00011001110
11001000011,00101101001,01111100110,10100101010,10110001111,11011101100,11110110001,10011110010,01000111111,01111011000,10101010100
01001101011,01100111101,10110110011,11001010011,00010011111,10101000111,10001111100,00111001001,11010100101,11110001010,01111110110
01111001001,10110100111,00110111100,10111010110,01011100010,11001101100,00101101011,10011111001,01000011111,11100111010,01101110101
10000111010,01011001110,11001010100,10010010111,11000101101,11011100001,00101100111,01110110100,00001111101,10111001000,01100011011
11010111001,10100011111,00110111100,11010010100,10011100111,11001101100,01011011010,10111001001,01110001111,11100100010,01101110101
00111001111,01111010101,10100011011,10011110011,11110100110,00101110110,11101101001,01000100111,10010111101,01110111010,11001011110
00100101101,01000001110,10001011101,01011000101,10110000011,10011101000,11101100100,00111110110,11010110101,01110011000,01001110011
00101111110,01100001011,01111010101,00011101001,00110100110,11111000010,11000110011,10110011000,01010011110,10001001111,11100101100
10110010110,00111111101,01010111110,11011011001,10101111010,01111100010,11101001100,10001100111,10110001011,01101011111,11100110001
01101011100,10101110101,10000111110,10101001011,11111100010,01001110011,00110111001,11110010111,11100101101,00011100111,11011011001
11001101100,01111011010,01100111101,00010101011,01001110011,11010011111,10101000111,00011110100,10100111010,10111011001,11110100000
10111110010,01110100111,11100101100,01001110110,10010011110,11000111011,00011111101,11011010101,01110011000,11011101010,00101001111
11010100100,01001111000,01111010010,01010001101,10011010011,00100110101,11101000101,00111101001,11100101011,10110011100,00001101110
11011100001,11000011111,01110101011,00001110111,01110000101,11101101100,10011001110,01011011000,10110111001,11101010010,11010110110
11011011001,11010101101,00101111001,10100001011,11110111010,01101001110,10001111110,01001100011,00010010111,10111100100,11100010101
11010010100,00010100111,01000111010,11011000011,10101110110,10001111101,01111101100,11100001111,10010001010,00111011111,10110110001
01101110110,11011000111,11110100001,00100101111,01010011101,00111010011,10011110101,11000111011,10110011110,01011101000,11101001001
11100010110,11110101000,01101110001,10010111101,11001001101,00111010100,01011011011,00100001111,01001111110,10011100111,10101011010
00010111010,10111001010,00111010100,11001011011,01101101000,01110000111,11001100110,10100111111,10011101101,11010011100,11110110001
11110000111,11011001001,00011011101,10010101110,01110111000,01001110011,10000111001,10111100001,01101101101,11001110100,10101011010
10110011110,11010111000,00111101100,01011010110,10011010101,11001001110,01111001001,01100111101,00010101011,11110100111,10101110010
11010110101,00101111101,10010101110,01000110110,11001001111,11100101100,10100110011,11011111000,01110011011,10111010110,01111100011
00111000011,00110101001,11011001010,01100011111,01110100110,10111010100,10010110011,10001101111,01011110101,00001111010,11101100001
01101111000,10110110001,10001011101,10011110110,00111011010,11111000101,11100011110,10110101100,11001101011,00101100111,01010111111
11110101101,00100010111,01111000001,10010110011,00011111101,01110111010,10101101001,11101110100,11000011001,01001101111,10011001110
10111001001,01110011011,10101010111,11011100010,10000101111,01011001101,01101100001,11001111000,00111111100,11010110101,11100001100
10100011101,01101100001,00000111011,11010101101,00111000111,11011010011,10011110100,11001001110,11100110110,10111101010,01111011000
00110101001,00010011111,11000111010,10111001110,10011011001,10110110100,11110000011,01111110010,11011100101,10101110011,01101011101
01100011111,11001001011,00001111110,10000001101,11010100110,01111001100,01011010111,00111100011,01010111001,10110011010,11101110000
00010001111,11110100110,00101111100,01111101001,01001110111,11000101101,11010111010,11101001010,10011010101,10100110011,01100011101
11101000011,01101101100,11011101001,11000011101,10111011000,01011001110,11000111010,01110110011,11011110100,10110100110,00001111111
00111100010,11110010110,11110101011,11011000111,00110011101,10000110111,10011011010,01101011011,01010111110,11011110001,11101101100
11001010111,10100111001,01101111000,10101001110,00111010101,01100101111,11110100010,11111001001,01110011010,00011101011,11010111100
"""  

# 按行分割
lines = [line.strip() for line in data.strip().split("\n") if line.strip()]

# 用集合去重（防止相同矩阵重复计算）
unique_lines = list(set(lines))

det_counts = {}

for line in unique_lines:
    # 把一行的逗号分隔部分转成二维矩阵
    rows = line.split(',')
    matrix = np.array([[int(c) for c in row] for row in rows])

    # 计算行列式
    det = round(np.linalg.det(matrix))  # 可四舍五入成整数
    det_counts[det] = det_counts.get(det, 0) + 1

# 打印结果
for det_val, count in sorted(det_counts.items()):
    print(f"det = {det_val}, count = {count}")
    
print(" number of different det:")
print(len(det_counts))
